name: Deploy Cloud Function with Terraform

on:
  push:
    branches:
      - main
      - master

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-key.json

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Decode and save GCP credentials
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS }}" > $GOOGLE_APPLICATION_CREDENTIALS

      - name: Authenticate with Google Cloud
        run: |
          gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
          gcloud config set project ${{ secrets.PROJECT_ID }}
          gcloud config set functions/region ${{ secrets.REGION }}

      - name: Package Cloud Function code
        run: |
          cd cloud_function
          zip -r ../templates/cloud_function_source.zip .
          cd ..

      - name: Terraform Init
        working-directory: ./infra
        run: terraform init

      - name: Terraform Validate
        working-directory: ./infra
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./infra
        run: terraform plan -var="project_id=${{ secrets.PROJECT_ID }}" -var="region=${{ secrets.REGION }}"

      - name: Terraform Apply
        working-directory: ./infra
        run: terraform apply -auto-approve -var="project_id=${{ secrets.PROJECT_ID }}" -var="region=${{ secrets.REGION }}"
